name: StrategicalIT
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75
title: >-
  Idea’s, thoughts and hopefully discussions related to IT in Business by
  Richard Houghton
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.375
  lightness: 0.3337515559978783
  saturation: 0.21697242138907313
  rhythmicContrast: 0.13177913520485163
purpose: []
